odataInstallGke:
  nfsSourceSnapshot: odata-green-20181001
  nfsSize: 100
  dbSize: 20
  datastoreSize: 50

odata:
  ckanDbPersistentDiskName: odata-blue-db
  ckanDataNfsServer: "10.23.242.160"
  ckanSecretName: ckan-secrets-2

  datastore:
    dbOps:
      backup: "gs://odata-k8s-backups/production/blue/datastore-db-dump-"
    persistentDiskName: odata-blue-datastore
    # see https://github.com/OriHoch/kube-ip-dns-updater
    dbKubeIpDnsUpdaterSecret: odata-datastore-db-kube-ip-dns-updater
    # see odata-blue-datastore-db-kube-ip-dns-updater-rbac.yaml
    dbKubeIpDnsUpdaterServiceAccountName: odata-blue-datastore-db-kube-ip-dns-updater
    dbEnableHostPort: true
    # kubectl create secret generic datastore-db-public-readonly-user --from-literal=DATASTORE_PUBLIC_RO_PASSWORD=***
    publicreadonlyDbUserPasswordSecretName: datastore-db-public-readonly-user

  dbOps:
    backup: "gs://odata-k8s-backups/production/blue/ckan-db-dump-"
