reportit:
  enabled: true
  botkit:
    enabled: true
    # persistent volume claim and disk names must be unique across all projects in the cluster
    persistentVolumeClaimName: reportit-botkit-data
    # create the disk first:
    # gcloud compute disks create --size=20GB --zone=europe-west1-b openpension-mongodb-data
    persistentVolumePersistentDiskName: reportit-botkit-data
    persistentVolumeSize: 1G
  strapi:
    enabled: true
    # persistent volume claim and disk names must be unique across all projects in the cluster
    persistentVolumeClaimName: reportit-strapi-data
    # create the disk first:
    # gcloud compute disks create --size=500GB --zone=europe-west1-b reportit-strapi-data
    persistentVolumePersistentDiskName: reportit-strapi-data
    persistentVolumeSize: 500G
  postgres:
    enabled: true
    # persistent volume claim and disk names must be unique across all projects in the cluster
    persistentVolumeClaimName: reportit-strapi-db
    # create the disk first:
    # gcloud compute disks create --size=5GB --zone=europe-west1-b reportit-strapi-db
    persistentVolumePersistentDiskName: reportit-strapi-db
    persistentVolumeSize: 5G
