migdar:
  enabled: true

traefik:
  # nfs needs an ip, be sure to update it in case of changes to the nfs service
  nfsServer: 10.23.253.67
  replicas: 1
  enableLoadBalancer: true
  acmeVolumeMountSubPath: test-traefik-acme

  letsencrypt:
    enabled: true
    acmeEmail: ori@uumpa.com
    dnsProvider: route53
    AWS_ACCESS_KEY_ID: AKIAIWMQWDTIM7IZS3EA
    AWS_REGION: "eu-west-1"
    awsSecretName: route53

  budgetkey:
    enabled: true
    frontendRule: "Host:next.obudget.org,data.obudget.org,socialmap.org.il,www.socialmap.org.il,kibana.obudget.org,dgp.obudget.org"
    backendUrl: "http://nginx.budgetkey:80"

  oknesset:
    enabled: true
    frontendRule: "Host:test.oknesset.org"
    backendUrl: "http://nginx.oknesset:80"
    acmeDomains: |
      [[acme.domains]]
        main = "test.oknesset.org"
