{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: client
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: client
        image: {{ .Values.client.image }}
        resources: {{ .Values.client.resources }}
        ports:
        - containerPort: 80
{{ end }}
