{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: backend
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: backend
        image: {{ .Values.backendImage | default "hasadna/datacity-backend" | quote }}
        resources: {"requests": {"cpu": "250m", "memory": "250Mi"}, "limits": {"memory": "500Mi"}}
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"DATABASE_URL"}}
        - name: GOOGLE_MAPS_API_KEY
          valueFrom: {"secretKeyRef":{"name":"datacity", "key":"GOOGLE_MAPS_API_KEY"}}
{{ end }}
