{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: frontend
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: frontend
        image: {{ .Values.frontendImage | default "hasadna/datacity-importer" | quote }}
        resources: {"requests": {"cpu": "50m", "memory": "50Mi"}, "limits": {"memory": "100Mi"}}
        env:
        - name: PORT
          value: "8000"
        - name: BACKEND
          value: backend:8000
{{ end }}
