{{ if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      {{ if .Values.globalTolerations }}tolerations: {{ .Values.globalTolerations }}{{ end }}
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        resources: {{ .Values.redisResources }}
{{ end }}
